[package]
name = "one-million-crabs"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
common-game = {git = "https://github.com/unitn-ap-2025/common.git"}

crossbeam-channel = "0.5.15"
env_logger = "0.11.8"